### ISSUE TITLE
Error - IoError: The layout was not found, File: $HOME/.config/zellij/layouts.yaml

### ISSUE THREAD

**Issue by Nurmukhamed** [tw4452852/zellij-pomodoro-plugin#1]
Hello, 
i'm trying to run plugin
my layout config is 

```yaml
---
template:
  - direction: Horizontal
    parts:
      - direction: Vertical
        borderless: true
        split_size:
          Fixed: 1
        run:
          plugin:
            location: "zellij:tab-bar"
      - direction: Vertical
        body: true
      - direction: Vertical
        borderless: true
        split_size:
          Fixed: 2
        run:
          plugin:
            location: "zellij:status-bar"
tabs:
  - direction: Vertical
    parts:
      - direction: Horizontal
        split_size:
          Percent: 35
      - direction: Horizontal
        split_size:
          Percent: 35
      - direction: Horizontal
        borderless: true
        split_size:
          Percent: 30
        run:
          plugin:
            path: /usr/share/zellij/plugins/pomodoro-clock.wasm
            _allow_exec_host_cmd: true

```
my zellij config is
```yaml
---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [NewPane: ]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g',]
    resize:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'n', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [Resize: Left,]
          key: [Char: 'h', Left,]
        - action: [Resize: Down,]
          key: [Char: 'j', Down,]
        - action: [Resize: Up,]
          key: [Char: 'k', Up, ]
        - action: [Resize: Right,]
          key: [Char: 'l', Right,]
        - action: [Resize: Increase,]
          key: [Char: '=']
        - action: [Resize: Increase,]
          key: [ Char: '+']
        - action: [Resize: Decrease,]
          key: [Char: '-']
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    pane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'p', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [MoveFocus: Left,]
          key: [ Char: 'h', Left,]
        - action: [MoveFocus: Right,]
          key: [ Char: 'l', Right,]
        - action: [MoveFocus: Down,]
          key: [ Char: 'j', Down,]
        - action: [MoveFocus: Up,]
          key: [ Char: 'k', Up,]
        - action: [SwitchFocus,]
          key: [Char: 'p']
        - action: [NewPane: , SwitchToMode: Normal,]
          key: [Char: 'n',]
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: 'd',]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: 'r',]
        - action: [CloseFocus, SwitchToMode: Normal,]
          key: [Char: 'x',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'f',]
        - action: [TogglePaneFrames, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [ToggleFloatingPanes, SwitchToMode: Normal,]
          key: [Char: 'w']
        - action: [TogglePaneEmbedOrFloating, SwitchToMode: Normal,]
          key: [Char: 'e']
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [SwitchToMode: RenamePane, PaneNameInput: [0],]
          key: [Char: 'c']
    move:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'h', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [Quit]
          key: [Ctrl: 'q']
        - action: [MovePane: ,]
          key: [Char: 'n', Char: "\t",]
        - action: [MovePane: Left,]
          key: [Char: 'h', Left,]
        - action: [MovePane: Down,]
          key: [Char: 'j', Down,]
        - action: [MovePane: Up,]
          key: [Char: 'k', Up, ]
        - action: [MovePane: Right,]
          key: [Char: 'l', Right,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    tab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 't', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: 'r']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [GoToPreviousTab,]
          key: [ Char: 'h', Left, Up, Char: 'k',]
        - action: [GoToNextTab,]
          key: [ Char: 'l', Right,Down, Char: 'j']
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'n',]
        - action: [CloseTab, SwitchToMode: Normal,]
          key: [ Char: 'x',]
        - action: [ToggleActiveSyncTab, SwitchToMode: Normal,]
          key: [Char: 's']
        - action: [GoToTab: 1, SwitchToMode: Normal,]
          key: [ Char: '1',]
        - action: [GoToTab: 2, SwitchToMode: Normal,]
          key: [ Char: '2',]
        - action: [GoToTab: 3, SwitchToMode: Normal,]
          key: [ Char: '3',]
        - action: [GoToTab: 4, SwitchToMode: Normal,]
          key: [ Char: '4',]
        - action: [GoToTab: 5, SwitchToMode: Normal,]
          key: [ Char: '5',]
        - action: [GoToTab: 6, SwitchToMode: Normal,]
          key: [ Char: '6',]
        - action: [GoToTab: 7, SwitchToMode: Normal,]
          key: [ Char: '7',]
        - action: [GoToTab: 8, SwitchToMode: Normal,]
          key: [ Char: '8',]
        - action: [GoToTab: 9, SwitchToMode: Normal,]
          key: [ Char: '9',]
        - action: [ToggleTab]
          key: [ Char: "\t" ]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    scroll:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 's', Char: ' ', Char: "\n", Esc]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Session,]
          key: [Ctrl: 'o',]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [ScrollToBottom, SwitchToMode: Normal,]
          key: [Ctrl: 'c',]
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [ScrollDown,]
          key: [Char: 'j', Down,]
        - action: [ScrollUp,]
          key: [Char: 'k', Up,]
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown, Right, Char: 'l',]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp, Left, Char: 'h',]
        - action: [HalfPageScrollDown,]
          key: [Char: 'd',]
        - action: [HalfPageScrollUp,]
          key: [Char: 'u',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    renamepane:
        - action: [SwitchToMode: Normal,]
          key: [Char: "\n", Ctrl: 'c', Esc]
        - action: [PaneNameInput: [27] , SwitchToMode: Pane,]
          key: [Esc,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    session:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'b',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Detach,]
          key: [Char: 'd',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    tmux:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: "\"",]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: '%',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'c',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: ',']
        - action: [GoToPreviousTab, SwitchToMode: Normal,]
          key: [ Char: 'p']
        - action: [GoToNextTab, SwitchToMode: Normal,]
          key: [ Char: 'n']
        - action: [MoveFocus: Left, SwitchToMode: Normal,]
          key: [ Left,]
        - action: [MoveFocus: Right, SwitchToMode: Normal,]
          key: [ Right,]
        - action: [MoveFocus: Down, SwitchToMode: Normal,]
          key: [ Down,]
        - action: [MoveFocus: Up, SwitchToMode: Normal,]
          key: [ Up,]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocus: Left,]
          key: [ Alt: 'h',]
        - action: [MoveFocus: Right,]
          key: [ Alt: 'l',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k',]
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider
    - path: pomodoro-clock
      tag: pmodoro-clock

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
#simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
default_shell: bash

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
#pane_frames: true

# Choose the theme that is specified in the themes section.
# Default: default
#theme: default

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true (default)
#   - false
#mouse_mode: false

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000

# Provide a command to execute when copying text. The text will be piped to
# the stdin of the program to perform the copy. This can be used with
# terminal emulators which do not support the OSC 52 ANSI control sequence
# that will be used by default if this option is not set.
# Examples:
#copy_command: "xclip -selection clipboard" # x11
#copy_command: "wl-copy"                    # wayland
#copy_command: "pbcopy"                     # osx

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
# copy_clipboard: primary

```
my startup command is 

```bash
#!/bin/bash

/usr/bin/zellij \
	--config ~/.config/zellij/config.yaml \
	--layout ~/.config/zellij/layouts.yaml
```

what may be cause of problem??

**Comment by Nurmukhamed** [comment]
I made some fix

1. i created new configuration
2. changed layout file

**zellij config**
```bash
mv ~/.config/zellij/ ~/.config/zellij-bak
zellij setup --check
mkdir ~/.config/zellij
zellij setup --check
zellij setup --dump-config > ~/.config/zellij/config.yaml
zellij setup --check
```

**layout config**
```yaml
---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - direction: Vertical
    parts:
      - direction: Horizontal
        split_size:
          Percent: 30
        run:
          plugin:
            location: "file:/home/username/.local/share/zellij/plugins/pomodoro-clock.wasm"
            _allow_exec_host_cmd: true
      - direction: Horizontal
        split_size:
          Percent: 35
      - direction: Horizontal
        split_size:
          Percent: 35
```

now pomodoro clock is working
